// <auto-generated />
using System;
using Custody.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Custody.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustodyDbContext))]
    partial class CustodyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Custody.Infrastructure.Persistence.ProofRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Point>("CapturedPoint")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("captured_point");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<Guid?>("OperatorOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_org_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<string>("PiiKeyVersion")
                        .HasColumnType("text")
                        .HasColumnName("pii_key_version");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proof_type");

                    b.Property<byte[]>("RecipientNameCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("recipient_name_ciphertext");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("UploadSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("UploadSessionId")
                        .IsUnique();

                    b.HasIndex("OwnerOrganizationId", "OrderId", "CreatedAt")
                        .HasDatabaseName("proofs_tenant_order_idx");

                    b.ToTable("proofs", "custody");
                });

            modelBuilder.Entity("Custody.Infrastructure.Persistence.ProofUploadSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_content_type");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("MaximumBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("maximum_bytes");

                    b.Property<Guid?>("OperatorOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_org_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<string>("QuarantineObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key_quarantine");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuarantineObjectKey")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("proof_upload_sessions_expiry_idx");

                    b.ToTable("proof_upload_sessions", "custody");
                });
#pragma warning restore 612, 618
        }
    }
}
