import type { NextConfig } from "next";

// next.config.ts is loaded by `next start` from the runtime image, which ships
// only .next/ and this file (deploy/azure/Dockerfile.web): it must not import
// application sources.

/**
 * The synthetic /dev portal lives in src/app/dev/page.dev.tsx. Its `dev.tsx`
 * page extension is registered only for `next dev` or an exact
 * PAQUETERIA_DEV_PORTAL_BUILD=true build (DevSynthetic images), so a normal
 * production build has no /dev route and ships none of its synthetic profiles
 * or mock credentials. The runtime gate in the page still applies.
 */
export function resolvePageExtensions(includeDevPortal: boolean): string[] {
  const standard = ["tsx", "ts", "jsx", "js"];
  return includeDevPortal ? ["dev.tsx", ...standard] : standard;
}

const defaultPermissionsPolicy =
  "geolocation=(), camera=(), microphone=(), payment=(), usb=()";
// The driver PWA is the only surface that may ask for its own location.
const driverPermissionsPolicy =
  "geolocation=(self), camera=(), microphone=(), payment=(), usb=()";

/**
 * Same-origin routing for the AuthCenter BFF (AUTH-001).
 *
 * The browser must reach the API on the web origin so the `__Host-` session
 * cookie is first-party and CSRF/Origin checks hold. In Azure the ingress routes
 * these prefixes to Paqueteria.Api (pilot decision); the Next rewrites below are
 * for local development only, enabled by `PAQUETENVIA_API_PROXY_ORIGIN`. Next
 * resolves rewrites when the config is evaluated by `next dev`/`next build` (they
 * are baked into the routes manifest); the value is server-only and never reaches
 * the browser bundle.
 */
export const apiProxyPrefixes = [
  "/api/:path*",
  "/hubs/:path*",
  "/auth/:path*",
  "/signin-authcenter",
] as const;

export interface ProxyRewrite {
  readonly source: string;
  readonly destination: string;
}

export function parseApiProxyOrigin(value: string | undefined): string | undefined {
  const candidate = value?.trim();
  if (!candidate) {
    return undefined;
  }
  let url: URL;
  try {
    url = new URL(candidate);
  } catch {
    throw new Error("PAQUETENVIA_API_PROXY_ORIGIN must be an absolute URL.");
  }
  if (
    (url.protocol !== "http:" && url.protocol !== "https:") ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    (url.pathname !== "/" && url.pathname !== "")
  ) {
    throw new Error("PAQUETENVIA_API_PROXY_ORIGIN must be a bare http(s) origin.");
  }
  return url.origin;
}

export function buildApiProxyRewrites(origin: string | undefined): ProxyRewrite[] {
  if (origin === undefined) {
    return [];
  }
  return apiProxyPrefixes.map((source) => ({
    source,
    destination: `${origin}${source}`,
  }));
}

export function assertSameOriginApiForBff(
  authMode: string | undefined,
  publicApiBaseUrl: string | undefined,
): void {
  if (authMode === "bff" && publicApiBaseUrl !== undefined && publicApiBaseUrl.trim() !== "") {
    throw new Error(
      "NEXT_PUBLIC_API_BASE_URL must be unset when NEXT_PUBLIC_AUTH_MODE=bff: the API is reached through the same origin.",
    );
  }
}

const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
if (
  apiBaseUrl !== undefined &&
  process.env.NODE_ENV === "production" &&
  new URL(apiBaseUrl).protocol !== "https:"
) {
  throw new Error("NEXT_PUBLIC_API_BASE_URL must use HTTPS in production.");
}
// AUTH-001: in BFF mode the browser reaches the API only through this origin.
assertSameOriginApiForBff(process.env.NEXT_PUBLIC_AUTH_MODE, apiBaseUrl);
const apiProxyRewrites = buildApiProxyRewrites(
  parseApiProxyOrigin(process.env.PAQUETENVIA_API_PROXY_ORIGIN),
);
const supportUrl = process.env.NEXT_PUBLIC_TRACKING_SUPPORT_URL;
if (supportUrl !== undefined) {
  const parsedSupportUrl = new URL(supportUrl);
  if (
    (parsedSupportUrl.protocol !== "https:" &&
      parsedSupportUrl.protocol !== "mailto:") ||
    parsedSupportUrl.searchParams.has("token") ||
    parsedSupportUrl.searchParams.has("access_token")
  ) {
    throw new Error("NEXT_PUBLIC_TRACKING_SUPPORT_URL is not safe.");
  }
}
// The Content-Security-Policy is nonce-based and emitted per request by
// src/proxy.ts (see src/security/security-headers.ts). Only static headers are
// declared here; a second CSP header would be enforced in addition to it.
const staticSecurityHeaders = [
  { key: "Referrer-Policy", value: "no-referrer" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // /dev is compiled only for `next dev` or an exact explicit build opt-in.
  pageExtensions: resolvePageExtensions(
    process.env.NODE_ENV === "development" ||
      process.env.PAQUETERIA_DEV_PORTAL_BUILD === "true",
  ),
  // `next dev` writes AGENTS.md/CLAUDE.md when it detects a coding agent.
  // Agent instructions must be authored and reviewed, never regenerated by a
  // dependency, so the generation is disabled instead of ignored.
  agentRules: false,
  logging: {
    incomingRequests: {
      ignore: [/^\/track(?:\/|$)/],
    },
  },
  async rewrites() {
    return [
      {
        source: "/track/:token",
        destination: "/track",
      },
      ...apiProxyRewrites,
    ];
  },
  async headers() {
    const privateNoStore = [
      { key: "Cache-Control", value: "no-store, private" },
      { key: "Pragma", value: "no-cache" },
      { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
    ];
    return [
      {
        source: "/:path*",
        headers: [
          ...staticSecurityHeaders,
          { key: "Permissions-Policy", value: defaultPermissionsPolicy },
        ],
      },
      {
        // Later matching entries override the same key: the driver PWA may
        // ask for its own location, nothing else may.
        source: "/driver/:path*",
        headers: [{ key: "Permissions-Policy", value: driverPermissionsPolicy }],
      },
      { source: "/track/:path*", headers: privateNoStore },
      { source: "/ops/:path*", headers: privateNoStore },
      { source: "/finance/:path*", headers: privateNoStore },
    ];
  },
};

export default nextConfig;
