import type { NextConfig } from "next";

/**
 * Same-origin routing for the AuthCenter BFF (AUTH-001).
 *
 * Lives in this file on purpose: the runtime image (deploy/azure/Dockerfile.web)
 * ships only `.next`, `node_modules`, `public` and `next.config.ts`, and
 * `next start` evaluates this config, so it must not import from `src/`.
 *
 * The browser must reach the API on the web origin so the `__Host-` session
 * cookie is first-party and CSRF/Origin checks hold. In Azure the ingress routes
 * these prefixes to Paqueteria.Api (pilot decision); the Next rewrites below are
 * for local development only, enabled by `PAQUETENVIA_API_PROXY_ORIGIN`. Next
 * resolves rewrites when the config is evaluated by `next dev`/`next build` (they
 * are baked into the routes manifest); the value is server-only and never reaches
 * the browser bundle.
 */
export const apiProxyPrefixes = [
  "/api/:path*",
  "/hubs/:path*",
  "/auth/:path*",
  "/signin-authcenter",
] as const;

export interface ProxyRewrite {
  readonly source: string;
  readonly destination: string;
}

export function parseApiProxyOrigin(value: string | undefined): string | undefined {
  const candidate = value?.trim();
  if (!candidate) {
    return undefined;
  }
  let url: URL;
  try {
    url = new URL(candidate);
  } catch {
    throw new Error("PAQUETENVIA_API_PROXY_ORIGIN must be an absolute URL.");
  }
  if (
    (url.protocol !== "http:" && url.protocol !== "https:") ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    (url.pathname !== "/" && url.pathname !== "")
  ) {
    throw new Error("PAQUETENVIA_API_PROXY_ORIGIN must be a bare http(s) origin.");
  }
  return url.origin;
}

export function buildApiProxyRewrites(origin: string | undefined): ProxyRewrite[] {
  if (origin === undefined) {
    return [];
  }
  return apiProxyPrefixes.map((source) => ({
    source,
    destination: `${origin}${source}`,
  }));
}

export function assertSameOriginApiForBff(
  authMode: string | undefined,
  publicApiBaseUrl: string | undefined,
): void {
  if (authMode === "bff" && publicApiBaseUrl !== undefined && publicApiBaseUrl.trim() !== "") {
    throw new Error(
      "NEXT_PUBLIC_API_BASE_URL must be unset when NEXT_PUBLIC_AUTH_MODE=bff: the API is reached through the same origin.",
    );
  }
}


const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
if (
  apiBaseUrl !== undefined &&
  process.env.NODE_ENV === "production" &&
  new URL(apiBaseUrl).protocol !== "https:"
) {
  throw new Error("NEXT_PUBLIC_API_BASE_URL must use HTTPS in production.");
}
// AUTH-001: in BFF mode the browser reaches the API only through this origin.
assertSameOriginApiForBff(process.env.NEXT_PUBLIC_AUTH_MODE, apiBaseUrl);
const apiProxyRewrites = buildApiProxyRewrites(
  parseApiProxyOrigin(process.env.PAQUETENVIA_API_PROXY_ORIGIN),
);
const supportUrl = process.env.NEXT_PUBLIC_TRACKING_SUPPORT_URL;
if (supportUrl !== undefined) {
  const parsedSupportUrl = new URL(supportUrl);
  if (
    (parsedSupportUrl.protocol !== "https:" &&
      parsedSupportUrl.protocol !== "mailto:") ||
    parsedSupportUrl.searchParams.has("token") ||
    parsedSupportUrl.searchParams.has("access_token")
  ) {
    throw new Error("NEXT_PUBLIC_TRACKING_SUPPORT_URL is not safe.");
  }
}
const apiOrigin = apiBaseUrl === undefined ? undefined : new URL(apiBaseUrl).origin;
const websocketOrigin =
  apiOrigin === undefined
    ? undefined
    : apiOrigin.replace(/^http:/, "ws:").replace(/^https:/, "wss:");
const connectSources = ["'self'", apiOrigin, websocketOrigin]
  .filter((value): value is string => value !== undefined)
  .join(" ");
const trackingCsp = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${process.env.NODE_ENV === "development" ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'none'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src ${connectSources}`,
].join("; ");
const operationsCsp = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${process.env.NODE_ENV === "development" ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src ${connectSources}`,
].join("; ");

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // `next dev` writes AGENTS.md/CLAUDE.md when it detects a coding agent.
  // Agent instructions must be authored and reviewed, never regenerated by a
  // dependency, so the generation is disabled instead of ignored.
  agentRules: false,
  logging: {
    incomingRequests: {
      ignore: [/^\/track(?:\/|$)/],
    },
  },
  async rewrites() {
    return [
      {
        source: "/track/:token",
        destination: "/track",
      },
      ...apiProxyRewrites,
    ];
  },
  async headers() {
    return [
      {
        source: "/track/:path*",
        headers: [
          { key: "Cache-Control", value: "no-store, private" },
          { key: "Pragma", value: "no-cache" },
          { key: "Referrer-Policy", value: "no-referrer" },
          { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          {
            key: "Permissions-Policy",
            value:
              "geolocation=(), camera=(), microphone=(), payment=(), usb=()",
          },
          { key: "Content-Security-Policy", value: trackingCsp },
        ],
      },
      {
        source: "/ops/:path*",
        headers: [
          { key: "Cache-Control", value: "no-store, private" },
          { key: "Pragma", value: "no-cache" },
          { key: "Referrer-Policy", value: "no-referrer" },
          { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          {
            key: "Permissions-Policy",
            value:
              "geolocation=(), camera=(), microphone=(), payment=(), usb=()",
          },
          { key: "Content-Security-Policy", value: operationsCsp },
        ],
      },
    ];
  },
};

export default nextConfig;
