import type { NextConfig } from "next";

// next.config.ts is loaded by `next start` from the runtime image, which ships
// only .next/ and this file (deploy/azure/Dockerfile.web): it must not import
// application sources.

/**
 * The synthetic /dev portal lives in src/app/dev/page.dev.tsx. Its `dev.tsx`
 * page extension is registered only for `next dev` or an exact
 * PAQUETERIA_DEV_PORTAL_BUILD=true build (DevSynthetic images), so a normal
 * production build has no /dev route and ships none of its synthetic profiles
 * or mock credentials. The runtime gate in the page still applies.
 */
export function resolvePageExtensions(includeDevPortal: boolean): string[] {
  const standard = ["tsx", "ts", "jsx", "js"];
  return includeDevPortal ? ["dev.tsx", ...standard] : standard;
}

const defaultPermissionsPolicy =
  "geolocation=(), camera=(), microphone=(), payment=(), usb=()";
// The driver PWA is the only surface that may ask for its own location.
const driverPermissionsPolicy =
  "geolocation=(self), camera=(), microphone=(), payment=(), usb=()";

const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
if (
  apiBaseUrl !== undefined &&
  process.env.NODE_ENV === "production" &&
  new URL(apiBaseUrl).protocol !== "https:"
) {
  throw new Error("NEXT_PUBLIC_API_BASE_URL must use HTTPS in production.");
}
const supportUrl = process.env.NEXT_PUBLIC_TRACKING_SUPPORT_URL;
if (supportUrl !== undefined) {
  const parsedSupportUrl = new URL(supportUrl);
  if (
    (parsedSupportUrl.protocol !== "https:" &&
      parsedSupportUrl.protocol !== "mailto:") ||
    parsedSupportUrl.searchParams.has("token") ||
    parsedSupportUrl.searchParams.has("access_token")
  ) {
    throw new Error("NEXT_PUBLIC_TRACKING_SUPPORT_URL is not safe.");
  }
}
// The Content-Security-Policy is nonce-based and emitted per request by
// src/proxy.ts (see src/security/security-headers.ts). Only static headers are
// declared here; a second CSP header would be enforced in addition to it.
const staticSecurityHeaders = [
  { key: "Referrer-Policy", value: "no-referrer" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // /dev is compiled only for `next dev` or an exact explicit build opt-in.
  pageExtensions: resolvePageExtensions(
    process.env.NODE_ENV === "development" ||
      process.env.PAQUETERIA_DEV_PORTAL_BUILD === "true",
  ),
  // `next dev` writes AGENTS.md/CLAUDE.md when it detects a coding agent.
  // Agent instructions must be authored and reviewed, never regenerated by a
  // dependency, so the generation is disabled instead of ignored.
  agentRules: false,
  logging: {
    incomingRequests: {
      ignore: [/^\/track(?:\/|$)/],
    },
  },
  async rewrites() {
    return [
      {
        source: "/track/:token",
        destination: "/track",
      },
    ];
  },
  async headers() {
    const privateNoStore = [
      { key: "Cache-Control", value: "no-store, private" },
      { key: "Pragma", value: "no-cache" },
      { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
    ];
    return [
      {
        source: "/:path*",
        headers: [
          ...staticSecurityHeaders,
          { key: "Permissions-Policy", value: defaultPermissionsPolicy },
        ],
      },
      {
        // Later matching entries override the same key: the driver PWA may
        // ask for its own location, nothing else may.
        source: "/driver/:path*",
        headers: [{ key: "Permissions-Policy", value: driverPermissionsPolicy }],
      },
      { source: "/track/:path*", headers: privateNoStore },
      { source: "/ops/:path*", headers: privateNoStore },
    ];
  },
};

export default nextConfig;
