// ENV-001 pilot (PILOT-REAL-PEOPLE), stage 2 of 5: network, logs, registry, proof storage,
// private PostgreSQL, the VNet-injected Container Apps environment and the cost budget.
targetScope = 'resourceGroup'

param location string = resourceGroup().location

@secure()
@description('PostgreSQL administrator password, generated by the workflow and kept only in Key Vault (pg-admin-password).')
param postgresAdministratorPassword string

@description('Browser origin allowed to PUT proofs directly to Blob Storage with a user-delegation SAS.')
param publicOrigin string = 'https://paquetenvia.com'

@description('First day of the month the budget starts counting (YYYY-MM-01). Keep it stable across redeploys.')
param budgetStartDate string

@description('Monthly budget in USD (PILOT-BUDGET-100USD).')
@maxValue(100)
param budgetAmount int = 100

@description('Extra e-mail recipients for budget alerts; resource-group Owners are always notified.')
param budgetContactEmails array = []

@description('Log Analytics daily ingestion cap in GB; protects the budget from a log storm.')
param logDailyQuotaGb string = '0.3'

@description('Defender for Storage malware scanning cap in GB scanned per month.')
param malwareScanningCapGbPerMonth int = 10

@description('Resource id of the custom role granting only blobs/tags/read (created once by the bootstrap).')
param blobTagReaderRoleDefinitionId string

var suffix = uniqueString(subscription().id, resourceGroup().id)
var tags = {
  project: 'Paquetenvia'
  environment: 'PILOT'
  contract: 'ENV-001'
  dataClassification: 'REAL_PEOPLE'
  cleanupGroup: 'ENV-001'
}
var containerAppsSubnetPrefix = '10.60.0.0/23'
var postgresAdministratorLogin = 'pvpilotadmin'

var roles = {
  acrPull: '7f951dda-4ed3-4680-a7ca-43fe172d538d'
  storageBlobDataContributor: 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'
  storageBlobDelegator: 'db58b8e5-c6ad-4a2a-8342-4190687cbf4a'
}

resource apiIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' existing = {
  name: 'id-pv-pilot-api'
}

resource workerIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' existing = {
  name: 'id-pv-pilot-worker'
}

// ---------------------------------------------------------------- network (VNet created in security.bicep)
resource vnet 'Microsoft.Network/virtualNetworks@2024-07-01' existing = {
  name: 'vnet-pv-pilot'
}

resource containerAppsSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' existing = {
  parent: vnet
  name: 'snet-containerapps'
}

resource postgresSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' existing = {
  parent: vnet
  name: 'snet-postgres'
}

resource postgresDnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: 'pv-pilot.private.postgres.database.azure.com'
  location: 'global'
  tags: tags
}

resource postgresDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: postgresDnsZone
  name: 'vnet-pv-pilot'
  location: 'global'
  tags: tags
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: vnet.id
    }
  }
}

// ---------------------------------------------------------------- logs
resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2025-02-01' = {
  name: 'law-pv-pilot-${suffix}'
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    sku: {
      name: 'PerGB2018'
    }
    workspaceCapping: {
      dailyQuotaGb: json(logDailyQuotaGb)
    }
  }
}

// ---------------------------------------------------------------- registry
resource registry 'Microsoft.ContainerRegistry/registries@2025-04-01' = {
  name: 'pvpilot${suffix}'
  location: location
  tags: tags
  sku: {
    name: 'Basic'
  }
  properties: {
    adminUserEnabled: false
    anonymousPullEnabled: false
    // Basic has no network rules; the runner pushes over the public endpoint with an Entra token.
    publicNetworkAccess: 'Enabled'
  }
}

var pullIdentityNames = [
  'id-pv-pilot-api'
  'id-pv-pilot-worker'
  'id-pv-pilot-web'
  'id-pv-pilot-migrate'
  'id-pv-pilot-logins'
]

resource pullIdentities 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' existing = [for name in pullIdentityNames: {
  name: name
}]

resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for (name, i) in pullIdentityNames: {
  name: guid(registry.id, pullIdentities[i].id, roles.acrPull)
  scope: registry
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.acrPull)
    principalId: pullIdentities[i].properties.principalId
    principalType: 'ServicePrincipal'
  }
}]

// ---------------------------------------------------------------- proof storage (ADP-001-POD-BLOB-DEFENDER)
resource storage 'Microsoft.Storage/storageAccounts@2025-01-01' = {
  name: 'stpvpilot${take(suffix, 13)}'
  location: location
  tags: tags
  kind: 'StorageV2'
  sku: {
    name: 'Standard_LRS'
  }
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    allowCrossTenantReplication: false
    defaultToOAuthAuthentication: true
    isHnsEnabled: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
    // Drivers' phones PUT proof bytes directly with a short-lived user-delegation SAS (AI-01 §4.16:
    // the API never receives POD bytes), so the blob endpoint must be reachable from the internet.
    // Anonymous access and shared keys are disabled; every request needs Entra ID or a delegation SAS.
    publicNetworkAccess: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      // Inert by design (PILOT-BLOB-PUBLIC-ENDPOINT): with defaultAction Allow this rule grants nothing
      // extra. It is kept so that switching defaultAction to Deny later keeps the workloads' access over
      // the free Microsoft.Storage service endpoint, while cutting off only the browsers.
      virtualNetworkRules: [
        {
          id: containerAppsSubnet.id
          action: 'Allow'
        }
      ]
    }
    encryption: {
      keySource: 'Microsoft.Storage'
      services: {
        blob: {
          enabled: true
          keyType: 'Account'
        }
      }
    }
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2025-01-01' = {
  parent: storage
  name: 'default'
  properties: {
    isVersioningEnabled: false
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    cors: {
      corsRules: [
        {
          allowedOrigins: [
            publicOrigin
          ]
          allowedMethods: [
            'PUT'
          ]
          allowedHeaders: [
            'content-type'
            'x-ms-blob-type'
            'x-ms-meta-*'
            'x-ms-version'
            'x-ms-client-request-id'
          ]
          exposedHeaders: [
            'etag'
            'x-ms-request-id'
          ]
          maxAgeInSeconds: 300
        }
      ]
    }
  }
}

resource proofsContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: blobService
  name: 'proofs'
  properties: {
    publicAccess: 'None'
  }
}

resource defenderForStorage 'Microsoft.Security/defenderForStorageSettings@2025-01-01' = {
  name: 'current'
  scope: storage
  properties: {
    isEnabled: true
    overrideSubscriptionLevelSettings: true
    malwareScanning: {
      onUpload: {
        isEnabled: true
        capGBPerMonth: malwareScanningCapGbPerMonth
      }
    }
    sensitiveDataDiscovery: {
      isEnabled: false
    }
  }
}

// ADP-001 RBAC: API signs user-delegation SAS (Delegator on the account) limited by its own container
// permissions; Worker validates and moves proofs and reads only the Defender verdict tag.
resource apiBlobDelegator 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, apiIdentity.id, roles.storageBlobDelegator)
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.storageBlobDelegator)
    principalId: apiIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource apiProofsContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(proofsContainer.id, apiIdentity.id, roles.storageBlobDataContributor)
  scope: proofsContainer
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.storageBlobDataContributor)
    principalId: apiIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource workerProofsContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(proofsContainer.id, workerIdentity.id, roles.storageBlobDataContributor)
  scope: proofsContainer
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.storageBlobDataContributor)
    principalId: workerIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource workerProofsTagReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(proofsContainer.id, workerIdentity.id, 'blob-tag-reader')
  scope: proofsContainer
  properties: {
    roleDefinitionId: blobTagReaderRoleDefinitionId
    principalId: workerIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// ---------------------------------------------------------------- PostgreSQL (PILOT-DB-PRIVATE-NETWORK)
resource postgres 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: 'pg-pv-pilot-${suffix}'
  location: location
  tags: tags
  sku: {
    name: 'Standard_B1ms'
    tier: 'Burstable'
  }
  properties: {
    administratorLogin: postgresAdministratorLogin
    administratorLoginPassword: postgresAdministratorPassword
    version: '18'
    storage: {
      storageSizeGB: 32
      autoGrow: 'Enabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    network: {
      publicNetworkAccess: 'Disabled'
      delegatedSubnetResourceId: postgresSubnet.id
      privateDnsZoneArmResourceId: postgresDnsZone.id
    }
    authConfig: {
      activeDirectoryAuth: 'Disabled'
      passwordAuth: 'Enabled'
    }
    backup: {
      backupRetentionDays: 14
      geoRedundantBackup: 'Disabled'
    }
  }
  dependsOn: [
    postgresDnsLink
  ]
}

resource postgresDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: postgres
  name: 'paqueteria'
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

// Server parameters are applied one at a time: the service rejects concurrent configuration updates.
resource secureTransport 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  parent: postgres
  name: 'require_secure_transport'
  properties: {
    value: 'ON'
    source: 'user-override'
  }
  dependsOn: [
    postgresDatabase
  ]
}

resource allowedExtensions 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  parent: postgres
  name: 'azure.extensions'
  properties: {
    value: 'POSTGIS,PGCRYPTO'
    source: 'user-override'
  }
  dependsOn: [
    secureTransport
  ]
}

resource passwordEncryption 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = {
  parent: postgres
  name: 'password_encryption'
  properties: {
    value: 'SCRAM-SHA-256'
    source: 'user-override'
  }
  dependsOn: [
    allowedExtensions
  ]
}

// ---------------------------------------------------------------- Container Apps environment
resource containerEnvironment 'Microsoft.App/managedEnvironments@2025-07-01' = {
  name: 'cae-pv-pilot-${suffix}'
  location: location
  tags: tags
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
    vnetConfiguration: {
      infrastructureSubnetId: containerAppsSubnet.id
      internal: false
    }
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
    zoneRedundant: false
  }
}

// ---------------------------------------------------------------- budget (PILOT-BUDGET-100USD)
resource budget 'Microsoft.Consumption/budgets@2024-08-01' = {
  name: 'budget-pv-pilot'
  properties: {
    category: 'Cost'
    amount: budgetAmount
    timeGrain: 'Monthly'
    timePeriod: {
      startDate: budgetStartDate
    }
    notifications: {
      actual80: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 80
        thresholdType: 'Actual'
        contactEmails: budgetContactEmails
        contactRoles: [
          'Owner'
        ]
      }
      actual100: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 100
        thresholdType: 'Actual'
        contactEmails: budgetContactEmails
        contactRoles: [
          'Owner'
        ]
      }
      forecast100: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 100
        thresholdType: 'Forecasted'
        contactEmails: budgetContactEmails
        contactRoles: [
          'Owner'
        ]
      }
    }
  }
}

output registryName string = registry.name
output registryServer string = registry.properties.loginServer
output storageAccountName string = storage.name
output blobServiceUri string = 'https://${storage.name}.blob.${environment().suffixes.storage}'
output postgresName string = postgres.name
output postgresHost string = postgres.properties.fullyQualifiedDomainName
output postgresAdministratorLogin string = postgresAdministratorLogin
output containerEnvironmentName string = containerEnvironment.name
output containerEnvironmentStaticIp string = containerEnvironment.properties.staticIp
output customDomainVerificationId string = containerEnvironment.properties.customDomainConfiguration.customDomainVerificationId
output containerAppsSubnetPrefix string = containerAppsSubnetPrefix
