// <auto-generated />
using System;
using Drivers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drivers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DriversDbContext))]
    [Migration("20260725000156_AdoptCanonicalDriverPositions")]
    partial class AdoptCanonicalDriverPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drivers.Domain.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Status", "ExpiresAt")
                        .HasDatabaseName("driver_documents_eligibility_idx");

                    b.ToTable("driver_documents", "drivers");
                });

            modelBuilder.Entity("Drivers.Domain.DriverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("driver_type");

                    b.Property<Guid>("HomeCityId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_city_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("driver_profiles_user_id_key");

                    b.ToTable("driver_profiles", "drivers");
                });

            modelBuilder.Entity("Drivers.Domain.DriverServiceArea", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid>("ServiceAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_area_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("DriverId", "ServiceAreaId");

                    b.ToTable("driver_service_areas", "drivers");
                });

            modelBuilder.Entity("Drivers.Infrastructure.Persistence.DriverPositionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccuracyMeters")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("accuracy_m");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<decimal?>("HeadingDegrees")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("heading_degrees");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("point");

                    b.Property<bool>("PublishRealtime")
                        .HasColumnType("boolean")
                        .HasColumnName("publish_realtime");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<decimal?>("SpeedMetersPerSecond")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("speed_mps");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("driver_positions_captured_brin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CapturedAt"), "brin");

                    b.HasIndex("Point")
                        .HasDatabaseName("driver_positions_point_gix");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Point"), "gist");

                    b.HasIndex("DriverId", "ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("driver_positions_driver_event_key");

                    b.HasIndex("OrganizationId", "DriverId", "CapturedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("driver_positions_tenant_time_idx");

                    b.ToTable("driver_positions", "drivers");
                });

            modelBuilder.Entity("Drivers.Domain.DriverDocument", b =>
                {
                    b.HasOne("Drivers.Domain.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Drivers.Domain.DriverServiceArea", b =>
                {
                    b.HasOne("Drivers.Domain.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Drivers.Infrastructure.Persistence.DriverPositionRecord", b =>
                {
                    b.HasOne("Drivers.Domain.DriverProfile", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
