// <auto-generated />
using System;
using Locations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Locations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    partial class LocationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Locations.Domain.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "StateCode", "Name")
                        .IsUnique()
                        .HasDatabaseName("cities_country_code_state_code_name_key");

                    b.ToTable("cities", "locations");
                });

            modelBuilder.Entity("Locations.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AddressCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("address_ciphertext");

                    b.Property<string>("AddressSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_summary");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<byte[]>("ContactNameCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("contact_name_ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OperatingZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("operating_zone_id");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<byte[]>("PhoneCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_ciphertext");

                    b.Property<string>("PiiKeyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pii_key_version");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("point");

                    b.Property<Guid?>("ServiceAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_area_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OperatingZoneId");

                    b.HasIndex("Point")
                        .HasDatabaseName("locations_point_gix");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Point"), "gist");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("OwnerOrganizationId", "CityId")
                        .HasDatabaseName("locations_owner_city_idx");

                    b.ToTable("locations", "locations");
                });

            modelBuilder.Entity("Locations.Domain.OperatingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<MultiPolygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("polygon");

                    b.Property<Guid>("ServiceAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_area_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_type");

                    b.HasKey("Id");

                    b.HasIndex("Polygon")
                        .HasDatabaseName("operating_zones_polygon_gix");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Polygon"), "gist");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("OwnerOrganizationId", "ServiceAreaId", "Name")
                        .IsUnique()
                        .HasDatabaseName("operating_zones_owner_org_id_service_area_id_name_key");

                    b.ToTable("operating_zones", "locations");
                });

            modelBuilder.Entity("Locations.Domain.ServiceArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<MultiPolygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("polygon");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Polygon")
                        .HasDatabaseName("service_areas_polygon_gix");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Polygon"), "gist");

                    b.HasIndex("OwnerOrganizationId", "CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("service_areas_owner_org_id_city_id_name_key");

                    b.ToTable("service_areas", "locations");
                });

            modelBuilder.Entity("Locations.Domain.Location", b =>
                {
                    b.HasOne("Locations.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Locations.Domain.OperatingZone", null)
                        .WithMany()
                        .HasForeignKey("OperatingZoneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Locations.Domain.ServiceArea", null)
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Locations.Domain.OperatingZone", b =>
                {
                    b.HasOne("Locations.Domain.ServiceArea", null)
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Locations.Domain.ServiceArea", b =>
                {
                    b.HasOne("Locations.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
